language: node_js
node_js:
  - 13
services:
  - docker
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker --version # print the version for logging
  - cd udagram-users-api/
  - docker build -t udagram-users-api -f Dockerfile .
  - docker tag udagram-users-api sanchimenea/udagram-users-api:latest
  - cd ../udagram-feed-api/
  - docker build -t udagram-feed-api -f Dockerfile .
  - docker tag udagram-feed-api sanchimenea/udagram-feed-api:latest
  - cd ../udagram-frontend/
  - docker build -t udagram-frontend -f Dockerfile .
  - docker tag udagram-frontend sanchimenea/udagram-frontend:latest
  - cd ../reverse-proxy/
  - docker build -t reverse-proxy -f Dockerfile . 
  - docker tag reverse-proxy sanchimenea/reverse-proxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sanchimenea/udagram-users-api
  - docker push sanchimenea/udagram-feed-api
  - docker push sanchimenea/udagram-frontend